version: '3.8'

services:
  
  web:
    image: php:8.2-apache
    volumes:
      - ./web:/var/www/html
    command: /bin/sh -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db
      - ai
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: school
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network

  ai:
    build: ./ai_engine
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./ai_engine/model:/app/model
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge