# Utiliser une image Python légère
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copier uniquement le fichier des dépendances d'abord (optimisation du cache)
COPY requirements.txt .

# Installer les packages Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code
# Le .dockerignore que tu as créé fera en sorte que le dossier 'model/'
# ne sera pas copié ici, ce qui rend le build très rapide.
COPY . .

# IMPORTANT : Créer le dossier où le volume sera monté
RUN mkdir -p /app/model

# Exposer le port du serveur Flask
EXPOSE 5000

# Lancer le serveur
CMD ["python", "flask_server.py"]